env:
  global:
    - NAME=OctaneScript
    - NAME_LOWER=octanescript
    - MAINTAINER=lcarcaramo@gmail.com
    - VERSION=0.0.5
    - RELEASE="Alpha"
    - RELEASE_LOWER="alpha"
    - RELEASE_STATUS="DEV"
    - RELEASE_STATUS_LOWER="dev"
    - COMMIT_SHORT="${TRAVIS_COMMIT:0:7}"
    - ARCH=amd64
    - LICENSE="$PWD/LICENSE"
    - README="$PWD/README.md"
    - SRC_DIR="$PWD/src"
    - ICON="$PWD/images/octanescript_logo.ico"
    - BUILD_SCRIPT="$PWD/travis/build.sh"
    - PUBLISH_REPO="lcarcaramo@frs.sourceforge.net:/home/frs/project/octanescript"

jobs:
  include:
    - os: linux
      language: python
      dist: trusty
      env:
        - OS=linux
        - DEB_PACKAGE_DIR="$PWD/package_debian"
    - os: windows
      language: bash
      env: 
        - OS=windows
        - WINDOWS_INSTALLER_DIR="$PWD/windows_installer"
script: 
  - cd $SRC_DIR && chmod +x $BUILD_SCRIPT && bash $BUILD_SCRIPT
