language: python
env:
  global: 
    - TEST_DIR="$PWD/core/test"
    - HOME_DIR="$PWD"
before-script:
  - pip install -r requirements.txt
script: 
  - cd $TEST_DIR && python TestPrinter.py
  - cd $HOME_DIR && pyinstaller --onefile  --name octane  main.py
  - cp resources dist/ && cp core/usage dist/
after-script:
  - tar -czvf octane.tgz dist
  - echo "publish"
