language: python
env:
  global: 
    - TEST_DIR="$PWD/core/test"
    - HOME_DIR="$PWD"
    - FILE_NAME="octane-0.0.1-c$TRAVIS_COMMIT.tgz"
before-script:
  - pip install -r requirements.txt
script: 
  - cd $TEST_DIR && python TestPrinter.py
  - cd $HOME_DIR && pyinstaller --onefile  --name octane  main.py
  - cp -r resources dist/ && cp -r core/usage dist/
after-script:
  - tar -czvf  dist
  - curl -T $FILE_NAME "sftp://$USER:$USER_PW@frs.sourceforge.net/home/frs/project/octane-lang/alpha/$FILE_NAME"
