language: python
dist: trusty
env:
  global: 
    - HOME_DIR="$PWD"
    - TEST_DIR="$HOME_DIR/core/test"
    - COMMIT_SHORT="${TRAVIS_COMMIT:0:7}"
    - FILE_NAME="octane-0.0.1-alpha-c$COMMIT_SHORT.tgz"
script: ./travis/build-linux.sh
