language: python
dist: trusty
env:
  global: 
    - VERSION=0.0.3-alpha
    - LICENSE="$PWD/LICENSE"
    - README="$PWD/README.md"
    - SRC_DIR="$PWD/src"
    - TEST_DIR="$HOME_DIR/core/test"
    - BUILD_LINUX_SCRIPT="$PWD/travis/build-linux.sh"
    - COMMIT_SHORT="${TRAVIS_COMMIT:0:7}"
    - FILE_NAME_LINUX="octane-$VERSION-c$COMMIT_SHORT-linux-x86.tgz"
script: cd $SRC_DIR && chmod +x $BUILD_LINUX_SCRIPT && bash $BUILD_LINUX_SCRIPT
