language: python
dist: trusty
env:
  global: 
    - HOME_DIR="$PWD/src"
    - TEST_DIR="$HOME_DIR/core/test"
    - COMMIT_SHORT="${TRAVIS_COMMIT:0:7}"
    - FILE_NAME_LINUX="octane-0.0.1-alpha-c$COMMIT_SHORT-linux-x86.tgz"
script: cd $HOME_DIR && chmod +x travis/build-linux.sh && bash travis/build-linux.sh
